### PR TITLE
Adding Tag configuration InfluxDb publisher

### PR DESCRIPTION
**Pull request by cdsap**
Proposal to add Tags configuration for InfluxdbPublisher.
Address issue https://github.com/cdsap/Talaiot/issues/232

Example:
```
publishers {
        influxDbPublisher {
            dbName = "tracking"
            url = "http://localhost:8086"
            taskMetricName = "task"
            buildMetricName = "build"
            tags = [com.cdsap.talaiot.metrics.BuildMetrics.RemoteCacheHit]
        }
    }
```

kts version works properly, but in the Groovy version didn't retrieve properly the tags in the E2E tests.

### CODE REVIEW

**Review by mokkun — APPROVED** [review]
Didn't have enough time to review it properly, but the code changes LGTM 👍

**Comment by cdsap** [comment]
thanks, just need to test the groovy build again

**Comment by cdsap** [comment]
I will deploy one Gradle Plugin to test the functionality before release

**Comment by cdsap** [comment]
I tested with Groovy and looks ok. 
Published new version 1.4.2 for all the dependencies and plugins. 
@mokkun Before announce the release,  if you want you can do a quick regression on 1.4.2

**Pull request merged**
